export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_ERROR = 'ALL_PRODUCTS_ERROR';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_ERROR = 'PRODUCT_DETAIL_ERROR';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_ERROR = 'NEW_REVIEW_ERROR';

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST';
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS';
export const ADMIN_PRODUCTS_ERROR = 'ADMIN_PRODUCTS_ERROR';

export const CREATE_ADMIN_PRODUCT_REQUEST = 'CREATE_ADMIN_PRODUCT_REQUEST';
export const CREATE_ADMIN_PRODUCT_SUCCESS = 'CREATE_ADMIN_PRODUCT_SUCCESS';
export const CREATE_ADMIN_PRODUCT_ERROR = 'CREATE_ADMIN_PRODUCT_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
